export const rabbitMqPatterns = {
  utilisateur: {
    create: 'utilisateur.create',
    findAll: 'utilisateur.findAll',
    findOne: 'utilisateur.findOne',
    update: 'utilisateur.update',
    remove: 'utilisateur.remove',
  },
  aliment: {
    create: 'aliment.create',
    findAll: 'aliment.findAll',
    findOne: 'aliment.findOne',
    update: 'aliment.update',
    remove: 'aliment.remove',
  },
  exercice: {
    create: 'exercice.create',
    findAll: 'exercice.findAll',
    findOne: 'exercice.findOne',
    update: 'exercice.update',
    remove: 'exercice.remove',
  },
  logAliment: {
    create: 'logAliment.create',
    findAll: 'logAliment.findAll',
    findOne: 'logAliment.findOne',
    update: 'logAliment.update',
    remove: 'logAliment.remove',
  },
  logSeance: {
    create: 'logSeance.create',
    findAll: 'logSeance.findAll',
    findOne: 'logSeance.findOne',
    update: 'logSeance.update',
    remove: 'logSeance.remove',
  },
  logSante: {
    create: 'logSante.create',
    findAll: 'logSante.findAll',
    findOne: 'logSante.findOne',
    update: 'logSante.update',
    remove: 'logSante.remove',
  },
  profilSante: {
    create: 'profilSante.create',
    findAll: 'profilSante.findAll',
    findOne: 'profilSante.findOne',
    update: 'profilSante.update',
    remove: 'profilSante.remove',
  },
  etlLog: {
    create: 'etlLog.create',
    findAll: 'etlLog.findAll',
    findOne: 'etlLog.findOne',
    update: 'etlLog.update',
    remove: 'etlLog.remove',
  },
  recommandationsRegime: {
    create: 'recommandationsRegime.create',
    findAll: 'recommandationsRegime.findAll',
    findOne: 'recommandationsRegime.findOne',
    update: 'recommandationsRegime.update',
    remove: 'recommandationsRegime.remove',
  },
  historiqueSeanceExercice: {
    create: 'historiqueSeanceExercice.create',
    findAll: 'historiqueSeanceExercice.findAll',
    findOne: 'historiqueSeanceExercice.findOne',
    update: 'historiqueSeanceExercice.update',
    remove: 'historiqueSeanceExercice.remove',
  },
} as const;
